a little changed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,8 +6,42 @@ on:
       - develop
 
 jobs:
+  version:
+    runs-on: ubuntu-latest
+    outputs:
+      changes: ${{ steps.version.outputs.changes }} # map step output to job output
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.PAT }}
+
+      - name: Enable node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16
+
+      # This step will run changeset version, setting the step output to if there were changesets found
+      - name: Version command
+        id: version
+        run: |
+          npm install --no-package-lock --no-save @changesets/cli
+          echo ::set-output name=changes::$(npx changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
+      # Push the updated package.json, and CHANGESET.md files to github, this will trigger a new build
+      # the || echo 'No changes' is to ignore errors from git when trying to commit and there are no changes
+      - name: Push changes
+        if: steps.version.outputs.changes == 'true'
+        run: |
+          git config user.email cicd@xdefi.io
+          git config user.name "cicd"
+          git add -A
+          git commit -m "Version packages" || echo "No changes to commit"
+          git push
+  
   publish-gpr:
     runs-on: ubuntu-latest
+    needs: version
+    if: always() && needs.version.outputs.changes == 'false'
     permissions:
       packages: write
       contents: read
@@ -18,7 +52,7 @@ jobs:
           node-version: 16
           registry-url: 'https://npm.pkg.github.com'
           scope: '@xdefi-tech'
-
+      
       - name: Setup user
         run: |
           git config user.email cicd@xdefi.io
@@ -38,7 +72,7 @@ jobs:
       - name: Create Release Pull Request
         uses: changesets/action@v1
         with:
-          publish: yarn publish-packages
+          publish: changeset publish
           setupGitUser: false
         env:
           NPM_TOKEN: ${{ secrets.PKG_TOKEN }}
